name: Generate SBOM

on:
  push:
    branches: [master]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install CycloneDX Node module
        run: npm install -g @cyclonedx/bom

      - name: Install dependencies
        run: npm install

      - name: Generate SBOM
        run: cyclonedx-bom -o bom.json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: bom.json
